### ISSUE TITLE
Hi i have this error in console

### ISSUE THREAD

**Issue by RickyLaChow** [hakan-krgn/hHomes#2]
[15:28:26 WARN]: [hHomes] Task #2078276 for hHomes v1.1.5 generated an exception
java.lang.NullPointerException: Cannot invoke "com.hakan.signapi.nms.SetupSign$SignManager.startListener(org.bukkit.entity.Player)" because the return value of "com.hakan.signapi.nms.SetupSign.getSignManager()" is null
        at com.hakan.signapi.SignAPI$1$1.run(SignAPI.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:476) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"d76f8e0"]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by hakan-krgn** [comment]
Hi, I recoded the plugin. Probably, this error is fixed. You can download lastest version of plugin from github.
